window.PRODUCT_CONFIG = {
  meta:{id:'desire-bottom-color',version:'1.0.0',title:'你的欲望底色是什么？',brand:'深渊测试'},
  theme:{accent:'#ff4a3d',background:'#090708',text:'#ece5d8',heroObjectPosition:'50% 20%'},
  media:{poster:'assets/hero-poster.png',heroVideo:'assets/hero-motion.mp4'},
  intro:{eyebrow:'32 道题 · 约 5 分钟',cta:'开始测试',disclaimer:'本测试仅供娱乐与自我观察，不构成心理诊断或医疗建议。'},
  dimensions:[
    {id:'se',label:'色欲',english:'LUST',color:'#ff4a3d',icon:'◆'},
    {id:'wu',label:'物欲',english:'POSSESSION',color:'#e3b341',icon:'◆'},
    {id:'quan',label:'权力欲',english:'POWER',color:'#9f72ff',icon:'◆'},
    {id:'biao',label:'表现欲',english:'EXPRESSION',color:'#4da3ff',icon:'◆'},
    {id:'po',label:'破坏欲',english:'DESTRUCTION',color:'#4eb477',icon:'◆'},
    {id:'tou',label:'偷窥欲',english:'OBSERVATION',color:'#a3a3a3',icon:'◆'}
  ],
  questions:[
    {id:'q01',text:'午夜你做了一个缠绵悱恻的梦，醒来时心跳还没平复。你第一反应是？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{se:5}},
      {label:'比较像我，有点心虚',weights:{se:4}},
      {label:'有一点点，但不多',weights:{se:3}},
      {label:'不太像，我会避开',weights:{se:2}},
      {label:'完全不是，这说的谁',weights:{se:1}}
    ]},
    {id:'q02',text:'午夜有个声音说：用十年寿命，换一生不缺钱。你会？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{wu:5}},
      {label:'比较像我，有点心虚',weights:{wu:4}},
      {label:'有一点点，但不多',weights:{wu:3}},
      {label:'不太像，我会避开',weights:{wu:2}},
      {label:'完全不是，这说的谁',weights:{wu:1}}
    ]},
    {id:'q03',text:'朋友聚会点菜，所有人都在互相推让。这时你内心是？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{quan:5}},
      {label:'比较像我，有点心虚',weights:{quan:4}},
      {label:'有一点点，但不多',weights:{quan:3}},
      {label:'不太像，我会避开',weights:{quan:2}},
      {label:'完全不是，这说的谁',weights:{quan:1}}
    ]},
    {id:'q04',text:'你在人群中讲了一个笑话，全场大笑鼓掌。那一刻你感觉？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{biao:5}},
      {label:'比较像我，有点心虚',weights:{biao:4}},
      {label:'有一点点，但不多',weights:{biao:3}},
      {label:'不太像，我会避开',weights:{biao:2}},
      {label:'完全不是，这说的谁',weights:{biao:1}}
    ]},
    {id:'q05',text:'看到一面写着“禁止触碰”的崭新的墙，你脑子里闪过的第一个念头是？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{po:5}},
      {label:'比较像我，有点心虚',weights:{po:4}},
      {label:'有一点点，但不多',weights:{po:3}},
      {label:'不太像，我会避开',weights:{po:2}},
      {label:'完全不是，这说的谁',weights:{po:1}}
    ]},
    {id:'q06',text:'合租室友没关门，屋里传来压低的争吵声。你会？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{tou:5}},
      {label:'比较像我，有点心虚',weights:{tou:4}},
      {label:'有一点点，但不多',weights:{tou:3}},
      {label:'不太像，我会避开',weights:{tou:2}},
      {label:'完全不是，这说的谁',weights:{tou:1}}
    ]},
    {id:'q07',text:'喜欢的人深夜给你发“睡不着”，你会联想到？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{se:5}},
      {label:'比较像我，有点心虚',weights:{se:4}},
      {label:'有一点点，但不多',weights:{se:3}},
      {label:'不太像，我会避开',weights:{se:2}},
      {label:'完全不是，这说的谁',weights:{se:1}}
    ]},
    {id:'q08',text:'路过橱窗看到你买不起但非常想要的东西，你通常会？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{wu:5}},
      {label:'比较像我，有点心虚',weights:{wu:4}},
      {label:'有一点点，但不多',weights:{wu:3}},
      {label:'不太像，我会避开',weights:{wu:2}},
      {label:'完全不是，这说的谁',weights:{wu:1}}
    ]},
    {id:'q09',text:'小组作业没人牵头，眼看要烂尾。你会？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{quan:5}},
      {label:'比较像我，有点心虚',weights:{quan:4}},
      {label:'有一点点，但不多',weights:{quan:3}},
      {label:'不太像，我会避开',weights:{quan:2}},
      {label:'完全不是，这说的谁',weights:{quan:1}}
    ]},
    {id:'q10',text:'朋友圈发了一张很满意的自拍，却没人点赞。你会？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{biao:5}},
      {label:'比较像我，有点心虚',weights:{biao:4}},
      {label:'有一点点，但不多',weights:{biao:3}},
      {label:'不太像，我会避开',weights:{biao:2}},
      {label:'完全不是，这说的谁',weights:{biao:1}}
    ]},
    {id:'q11',text:'连续加班一周，领导又临时加活。你心里冒出的声音是？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{po:5}},
      {label:'比较像我，有点心虚',weights:{po:4}},
      {label:'有一点点，但不多',weights:{po:3}},
      {label:'不太像，我会避开',weights:{po:2}},
      {label:'完全不是，这说的谁',weights:{po:1}}
    ]},
    {id:'q12',text:'朋友把手机扣在桌上，前任发来消息预览一闪而过。你会？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{tou:5}},
      {label:'比较像我，有点心虚',weights:{tou:4}},
      {label:'有一点点，但不多',weights:{tou:3}},
      {label:'不太像，我会避开',weights:{tou:2}},
      {label:'完全不是，这说的谁',weights:{tou:1}}
    ]},
    {id:'q13',text:'伴侣出差一周，深夜你最想做的是？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{se:5}},
      {label:'比较像我，有点心虚',weights:{se:4}},
      {label:'有一点点，但不多',weights:{se:3}},
      {label:'不太像，我会避开',weights:{se:2}},
      {label:'完全不是，这说的谁',weights:{se:1}}
    ]},
    {id:'q14',text:'如果必须选择，你更害怕哪一种人生？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{wu:5}},
      {label:'比较像我，有点心虚',weights:{wu:4}},
      {label:'有一点点，但不多',weights:{wu:3}},
      {label:'不太像，我会避开',weights:{wu:2}},
      {label:'完全不是，这说的谁',weights:{wu:1}}
    ]},
    {id:'q15',text:'玩狼人杀/剧本杀时，你最享受的位置是？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{quan:5}},
      {label:'比较像我，有点心虚',weights:{quan:4}},
      {label:'有一点点，但不多',weights:{quan:3}},
      {label:'不太像，我会避开',weights:{quan:2}},
      {label:'完全不是，这说的谁',weights:{quan:1}}
    ]},
    {id:'q16',text:'公司年会需要有人上台表演，你的第一反应是？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{biao:5}},
      {label:'比较像我，有点心虚',weights:{biao:4}},
      {label:'有一点点，但不多',weights:{biao:3}},
      {label:'不太像，我会避开',weights:{biao:2}},
      {label:'完全不是，这说的谁',weights:{biao:1}}
    ]},
    {id:'q17',text:'有一份稳定但无聊的工作，和一份冒险但可能归零的机会。你倾向？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{po:5}},
      {label:'比较像我，有点心虚',weights:{po:4}},
      {label:'有一点点，但不多',weights:{po:3}},
      {label:'不太像，我会避开',weights:{po:2}},
      {label:'完全不是，这说的谁',weights:{po:1}}
    ]},
    {id:'q18',text:'你更喜欢哪种故事？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{tou:5}},
      {label:'比较像我，有点心虚',weights:{tou:4}},
      {label:'有一点点，但不多',weights:{tou:3}},
      {label:'不太像，我会避开',weights:{tou:2}},
      {label:'完全不是，这说的谁',weights:{tou:1}}
    ]},
    {id:'q19',text:'看到亲密戏份时，你通常是？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{se:5}},
      {label:'比较像我，有点心虚',weights:{se:4}},
      {label:'有一点点，但不多',weights:{se:3}},
      {label:'不太像，我会避开',weights:{se:2}},
      {label:'完全不是，这说的谁',weights:{se:1}}
    ]},
    {id:'q20',text:'深夜查银行卡余额时，你的情绪是？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{wu:5}},
      {label:'比较像我，有点心虚',weights:{wu:4}},
      {label:'有一点点，但不多',weights:{wu:3}},
      {label:'不太像，我会避开',weights:{wu:2}},
      {label:'完全不是，这说的谁',weights:{wu:1}}
    ]},
    {id:'q21',text:'有人当众反驳了你的观点，你的第一反应是？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{quan:5}},
      {label:'比较像我，有点心虚',weights:{quan:4}},
      {label:'有一点点，但不多',weights:{quan:3}},
      {label:'不太像，我会避开',weights:{quan:2}},
      {label:'完全不是，这说的谁',weights:{quan:1}}
    ]},
    {id:'q22',text:'你更希望别人这样评价你？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{biao:5}},
      {label:'比较像我，有点心虚',weights:{biao:4}},
      {label:'有一点点，但不多',weights:{biao:3}},
      {label:'不太像，我会避开',weights:{biao:2}},
      {label:'完全不是，这说的谁',weights:{biao:1}}
    ]},
    {id:'q23',text:'如果城市突然停电一夜，没有监控没有灯，你会觉得？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{po:5}},
      {label:'比较像我，有点心虚',weights:{po:4}},
      {label:'有一点点，但不多',weights:{po:3}},
      {label:'不太像，我会避开',weights:{po:2}},
      {label:'完全不是，这说的谁',weights:{po:1}}
    ]},
    {id:'q24',text:'地铁上旁边的人在聊劲爆八卦，你会？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{tou:5}},
      {label:'比较像我，有点心虚',weights:{tou:4}},
      {label:'有一点点，但不多',weights:{tou:3}},
      {label:'不太像，我会避开',weights:{tou:2}},
      {label:'完全不是，这说的谁',weights:{tou:1}}
    ]},
    {id:'q25',text:'你理想中的亲密关系更接近？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{se:5}},
      {label:'比较像我，有点心虚',weights:{se:4}},
      {label:'有一点点，但不多',weights:{se:3}},
      {label:'不太像，我会避开',weights:{se:2}},
      {label:'完全不是，这说的谁',weights:{se:1}}
    ]},
    {id:'q26',text:'朋友暴富请客炫富，你内心真实的波动是？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{wu:5}},
      {label:'比较像我，有点心虚',weights:{wu:4}},
      {label:'有一点点，但不多',weights:{wu:3}},
      {label:'不太像，我会避开',weights:{wu:2}},
      {label:'完全不是，这说的谁',weights:{wu:1}}
    ]},
    {id:'q27',text:'如果能拥有一种超能力，你更想要？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{quan:5}},
      {label:'比较像我，有点心虚',weights:{quan:4}},
      {label:'有一点点，但不多',weights:{quan:3}},
      {label:'不太像，我会避开',weights:{quan:2}},
      {label:'完全不是，这说的谁',weights:{quan:1}}
    ]},
    {id:'q28',text:'独处时你经常会？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{biao:5}},
      {label:'比较像我，有点心虚',weights:{biao:4}},
      {label:'有一点点，但不多',weights:{biao:3}},
      {label:'不太像，我会避开',weights:{biao:2}},
      {label:'完全不是，这说的谁',weights:{biao:1}}
    ]},
    {id:'q29',text:'看到规则、流程、禁忌时，你本能的感觉是？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{po:5}},
      {label:'比较像我，有点心虚',weights:{po:4}},
      {label:'有一点点，但不多',weights:{po:3}},
      {label:'不太像，我会避开',weights:{po:2}},
      {label:'完全不是，这说的谁',weights:{po:1}}
    ]},
    {id:'q30',text:'深夜独处、微醺、灯光昏暗时，你最容易想起？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{se:5}},
      {label:'比较像我，有点心虚',weights:{se:4}},
      {label:'有一点点，但不多',weights:{se:3}},
      {label:'不太像，我会避开',weights:{se:2}},
      {label:'完全不是，这说的谁',weights:{se:1}}
    ]},
    {id:'q31',text:'如果可以匿名做一件事不被发现，你最想？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{po:5}},
      {label:'比较像我，有点心虚',weights:{po:4}},
      {label:'有一点点，但不多',weights:{po:3}},
      {label:'不太像，我会避开',weights:{po:2}},
      {label:'完全不是，这说的谁',weights:{po:1}}
    ]},
    {id:'q32',text:'深夜刷手机，你停留最久的是哪类内容？',options:[
      {label:'完全是我，灵魂在尖叫',weights:{tou:5}},
      {label:'比较像我，有点心虚',weights:{tou:4}},
      {label:'有一点点，但不多',weights:{tou:3}},
      {label:'不太像，我会避开',weights:{tou:2}},
      {label:'完全不是，这说的谁',weights:{tou:1}}
    ]}
  ],
  results:[
    {id:'se-result',dimensionId:'se',title:'色欲 · 炽红',slogan:'“你渴望的不是身体，是被彻底记住的感觉。”',
      mono:'你的欲望底色是炽红。亲密、气味、眼神、深夜的消息，对你都有致命的引力。你表面克制，内心却有一座随时会喷发的火山。你不是滥情，你只是比别人更诚实地渴望被爱、被需要、被深深进入生活。',
      diag:'六维中你的【色欲】一骑绝尘。这意味着你的生命能量与爱、欲、联结深度绑定。开心时想抱人，难过时更想抱人。压抑它，你会枯萎；正视它，你会发光。',
      seyu:'色欲强度：★★★★★。你对亲密的嗅觉极其敏锐，能从一句话里听出暧昧。你需要警惕的是：把“被渴望”等同于“被爱”。偶尔的抽离，会让你更有魅力。',
      mid:'物欲 / 权力欲 / 表现欲：中等偏上。你想要钱和舞台，但归根结底都是为了爱——有钱才敢爱，有权才配爱，被看见才值得被爱。建议：别让欲望互相打架，先满足最红的那一块。',
      dark:'破坏欲：你偶尔想撕碎一段关系来证明它是否牢固，这是炽红的副作用。偷窥欲：你对喜欢的人有轻微“显微镜”倾向，想知道TA的一切。记住：留白也是亲密的一部分。',
      advice:'暗夜处方：1）把欲望说出口，写下来或告诉信任的人；2）区分“想要”和“需要”，睡前问自己三遍；3）用运动、舞蹈、创作疏通身体能量。你的红，是礼物，不是污点。愿你敢要，也敢不要。'},
    {id:'wu-result',dimensionId:'wu',title:'物欲 · 金黄',slogan:'“你想要的不是钱，是再也不用害怕的感觉。”',
      mono:'你的欲望底色是金黄。你对安全感有执念：存款数字、房子钥匙、冰箱里的存货，都能让你心安。别人说你现实，只有你知道，没钱的深夜有多冷。',
      diag:'六维中你的【物欲】最高。这不庸俗，这是生存智慧。你从小就明白：情绪价值填不饱肚子。你擅长规划、囤积、未雨绸缪，是朋友中的“靠山”。',
      seyu:'色欲倾向：中等。你也会心动，但心动之前会先算账：这个人靠谱吗？未来有保障吗？这不是冷漠，是你的自我保护。建议允许自己偶尔“不计成本”地心动一次。',
      mid:'物欲★★★★★，权力欲 / 表现欲中等。你不爱出风头，但你在意分量——工资条的分量、礼物的分量、话语的分量。提醒：别用囤积填补焦虑，钱是工具，不是主人。',
      dark:'破坏欲低：你讨厌归零，稳定压倒一切。偷窥欲中等偏高：你爱看别人的财富故事、翻购房攻略、研究副业，这是金黄在学习捕猎。注意别陷入比较地狱。',
      advice:'暗夜处方：1）设定“欲望预算”，每月允许一次不理性的快乐消费；2）把安全感从数字转移到能力上；3）练习谈钱不羞耻。你值得丰盛，也值得心安。'},
    {id:'quan-result',dimensionId:'quan',title:'权力欲 · 紫金',slogan:'“你不是想控制别人，你只是不想再失控。”',
      mono:'你的欲望底色是紫金。你享受说了算的感觉：带队、拍板、被征求意见。混乱让你焦虑，秩序让你性感。你天生有领袖气，只是还没坐上那把椅子。',
      diag:'六维中你的【权力欲】登顶。你对影响力、话语权、地位极其敏感。开会没人听你会难受，计划被打乱会烦躁。这不是强势，是你对“我能行”的确认需求。',
      seyu:'色欲倾向：中高。你在亲密中也想主导节奏，喜欢被依赖、被需要。注意：爱不是KPI，别把伴侣当下属。偶尔示弱，权力反而更稳。',
      mid:'权力★★★★★，物欲 / 表现欲双高。你想要的是“说了算且被喝彩”。建议：把控制欲转化为领导力——给方向，也给空间。真正的王，是让人自愿追随。',
      dark:'破坏欲中等：当规则束缚你，你会想掀桌。偷窥欲中等：你爱观察人心、研究人性，这是帝王术的本能。提醒：信息是用来理解人，不是拿捏人。',
      advice:'暗夜处方：1）每天练习一次“不指挥”，观察会发生什么；2）把“我要赢”换成“我们要成”；3）找到一个能让你放心交出方向盘的人。愿你的紫金，是庇护，不是枷锁。'},
    {id:'biao-result',dimensionId:'biao',title:'表现欲 · 靛蓝',slogan:'“你害怕的不是孤独，是在人群中隐形。”',
      mono:'你的欲望底色是靛蓝。你是天生的发光体：朋友圈的氛围组，聚会的气氛担当。你需要掌声、点赞、被记住。熄灯后的失落，只有你自己知道。',
      diag:'六维中你的【表现欲】最亮。你的能量来自注视。被夸一句能开心三天，被无视一次能内耗一周。你不是虚荣，你只是用“被看见”来确认“我存在”。',
      seyu:'色欲倾向：中高。你渴望戏剧性的爱情：心动、表白、纪念日，一个不能少。你容易把暧昧当舞台。建议：练习“无人喝彩也绽放”，爱自己才是终身巡演。',
      mid:'表现★★★★★，物欲 / 权力中等。你想要的不仅是拥有，还要被羡慕。提醒：别为了人设透支生活。滤镜会碎，但你的真实很动人。',
      dark:'破坏欲低：你爱惜羽毛，不轻易决裂。偷窥欲高：你会反复看谁看了你的动态、谁没回你消息。建议：把70%的“求关注”转成“给关注”，回流会惊人。',
      advice:'暗夜处方：1）每天做一件不发朋友圈的快乐小事；2）把才华变成作品，而不是动态；3）找一个不需表演也能待着的人。愿你的靛蓝，照亮别人，也温暖自己。'},
    {id:'po-result',dimensionId:'po',title:'破坏欲 · 墨绿',slogan:'“你想砸碎的不是世界，是困住你的那间房。”',
      mono:'你的欲望底色是墨绿。你骨子里有一种野性：讨厌重复、讨厌规矩、讨厌“就该这样”。别人求稳，你求真。压抑久了，你会想一夜之间全部推倒重来。',
      diag:'六维中你的【破坏欲】最高。这不代表暴力，代表你对自由和真实的极端渴望。无效会议、窒息关系、烂尾工作，都会触发你的“掀桌按钮”。',
      seyu:'色欲倾向：中高且激烈。你要么极度热烈，要么瞬间冰冷，爱恨都带着毁灭美学。建议：把“摧毁”换成“重建”，分手前先说出需求，辞职前先谈一次。',
      mid:'破坏★★★★★，物欲 / 权力 / 表现都不低。你不是要赢，你是要“不玩了”。提醒：自由的代价是负责。砸碎之前，先想好往哪里走。',
      dark:'破坏与偷窥双高是典型“暗夜观察者”：白天安静，晚上在心里演一百出离经叛道。你对禁忌、悬疑、深渊话题毫无抵抗力。把这份敏锐用来创作，会很惊人。',
      advice:'暗夜处方：1）每周一次“合法破坏”：高强度运动、密室、写作宣泄；2）给愤怒命名，别让它替你做决定；3）留一个“重启按钮”而不是“自毁按钮”。愿你的墨绿，长成森林，而非荒原。'},
    {id:'tou-result',dimensionId:'tou',title:'偷窥欲 · 深灰',slogan:'“你不八卦，你只是想提前知道结局。”',
      mono:'你的欲望底色是深灰。你是人群中的静默雷达：谁和谁分手了，谁升职了，谁深夜emo了，你都知道。你不爱说话，但你什么都看见了。',
      diag:'六维中你的【偷窥欲】最高。你的快感来自“知情”：翻前任动态、看评论区吵架、研究别人的故事。这背后是对失控的恐惧——知道得多，才觉得安全。',
      seyu:'色欲倾向：中等偏闷骚。你不主动，但你记得TA所有细节：头像换了、歌单变了、几点在线。你是暗恋高手。建议：把观察变成靠近，问一句比看十天有用。',
      mid:'偷窥★★★★★，其他欲望普遍内敛。你不争不抢，但你在心里给所有人打分。提醒：看多了别人的剧本，会忘了写自己的。',
      dark:'破坏欲低：你是安全的树洞。偷窥欲高配表现欲低，是经典“隐身人”配置。注意：别用窥视代替连接，别用“懂了”代替“拥有”。',
      advice:'暗夜处方：1）每天减少30分钟“围观时间”，用来记录自己；2）练习主动暴露一点点脆弱；3）把洞察力变成天赋：写作、咨询、创作。愿你的深灰，是智慧的雾，不是困住自己的茧。同时：请尊重他人隐私，凝视深渊时别越界。'}
  ],
  sharing:{template:'【深渊测试】我的欲望底色是：{resultTitle}\n{resultSlogan}\n32题测出你的底色，你敢吗？'},
  legal:{license:'个人使用，禁止转售、二次打包和去除署名后公开分发。'}
};
